[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "uav-routing"
version = "0.1.0"
dependencies = []

[tool.setuptools.packages.find]
include = ["uav_routing*"]
exclude = ["datasets*"]